// <auto-generated />
using GuessX.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GuessX.Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251101031245_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GuessX.Server.Entities.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("PK__genres__3213E83F11A1BFCE");

                    b.HasIndex(new[] { "Name" }, "UQ__genres__72E12F1BA4FD6A64")
                        .IsUnique();

                    b.ToTable("genres", (string)null);
                });

            modelBuilder.Entity("GuessX.Server.Entities.TitleAnswer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("answer");

                    b.Property<int>("TitleId")
                        .HasColumnType("int")
                        .HasColumnName("title_id");

                    b.HasKey("Id")
                        .HasName("PK__title_an__3213E83F43C4A7EC");

                    b.HasIndex("TitleId");

                    b.ToTable("title_answers", (string)null);
                });

            modelBuilder.Entity("GuessX.Server.Entities.TitleImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImageType")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("image_type");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("image_url");

                    b.Property<int>("TitleId")
                        .HasColumnType("int")
                        .HasColumnName("title_id");

                    b.HasKey("Id")
                        .HasName("PK__title_im__3213E83F2615F9A0");

                    b.HasIndex("TitleId");

                    b.HasIndex(new[] { "ImageUrl" }, "idx_image_url");

                    b.ToTable("title_images", (string)null);
                });

            modelBuilder.Entity("GuessX.Server.Entities.TitlePictureGallery", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("category");

                    b.Property<string>("TitleName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("title_name");

                    b.HasKey("Id")
                        .HasName("PK__title_pi__3213E83F65F656E0");

                    b.ToTable("title_picture_gallery", (string)null);
                });

            modelBuilder.Entity("TitleGenre", b =>
                {
                    b.Property<int>("TitleId")
                        .HasColumnType("int")
                        .HasColumnName("title_id");

                    b.Property<int>("GenreId")
                        .HasColumnType("int")
                        .HasColumnName("genre_id");

                    b.HasKey("TitleId", "GenreId")
                        .HasName("PK__title_ge__21E6F1A3D62E87BC");

                    b.HasIndex("GenreId");

                    b.ToTable("title_genres", (string)null);
                });

            modelBuilder.Entity("GuessX.Server.Entities.TitleAnswer", b =>
                {
                    b.HasOne("GuessX.Server.Entities.TitlePictureGallery", "Title")
                        .WithMany("TitleAnswers")
                        .HasForeignKey("TitleId")
                        .IsRequired()
                        .HasConstraintName("FK__title_ans__title__7B5B524B");

                    b.Navigation("Title");
                });

            modelBuilder.Entity("GuessX.Server.Entities.TitleImage", b =>
                {
                    b.HasOne("GuessX.Server.Entities.TitlePictureGallery", "Title")
                        .WithMany("TitleImages")
                        .HasForeignKey("TitleId")
                        .IsRequired()
                        .HasConstraintName("FK__title_ima__title__787EE5A0");

                    b.Navigation("Title");
                });

            modelBuilder.Entity("TitleGenre", b =>
                {
                    b.HasOne("GuessX.Server.Entities.Genre", null)
                        .WithMany()
                        .HasForeignKey("GenreId")
                        .IsRequired()
                        .HasConstraintName("FK__title_gen__genre__75A278F5");

                    b.HasOne("GuessX.Server.Entities.TitlePictureGallery", null)
                        .WithMany()
                        .HasForeignKey("TitleId")
                        .IsRequired()
                        .HasConstraintName("FK__title_gen__title__74AE54BC");
                });

            modelBuilder.Entity("GuessX.Server.Entities.TitlePictureGallery", b =>
                {
                    b.Navigation("TitleAnswers");

                    b.Navigation("TitleImages");
                });
#pragma warning restore 612, 618
        }
    }
}
